### ISSUE TITLE
Forgotten pod trunk push?

### ISSUE THREAD

**Issue by fvolchyok** [AckeeCZ/Reqres#27]
Event though version 3.1.1 seems like ready-to-use I can't download it from cocoapods main repo, probably due to forgotten `pod trunk push`. From there I can download only 3.1.0 (https://cocoapods.org/pods/Reqres)

**Comment by olejnjak** [comment]
Hi @fvolchyok, 

thanks for the issue, we'll look into it in a moment, but for now I'll close this issue as it is a duplicate of #26.
