### ISSUE TITLE
Custom URLSession

### ISSUE THREAD

**Issue by Yurssoft** [AckeeCZ/Reqres#7]
What about custom URLSession? If I use custom URLSession how can I log all requests and responses? As for now, no logging is occurring with custom URLSession.

`let urlSession = URLSession(configuration: URLSessionConfiguration.default)`

I'd like to have something like this:

`urlSession.logger = Reqres.logger`

**Comment by janmisar** [comment]
Try this, it should solve your problem

`let urlSession = URLSession(configuration: Reqres.defaultSessionConfiguration())`

If I understand right, this function does exactly what you need.

```swift
open class func defaultSessionConfiguration() -> URLSessionConfiguration {
     let config = URLSessionConfiguration.default
     config.protocolClasses?.insert(Reqres.self, at: 0)
     return config
}
```

**Comment by Yurssoft** [comment]
Worked! Thanks a lot! Also, you can add this to readme for other people not to ask the same question.
